---
- name: Initialize Kubernetes cluster on master node
  hosts: k8s_master
  become: yes
  tasks:
    - name: Reset kubeadm (optional)
      shell: kubeadm reset -f
      ignore_errors: yes

    - name: Initialize cluster
      shell: |
        kubeadm init \
          --pod-network-cidr=192.168.0.0/16 \
          --apiserver-advertise-address={{ ansible_default_ipv4.address }}
      register: kubeadm_init

    - name: Create .kube directory for user
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: 0755

    - name: Copy admin config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_user }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Install Calico Network Plugin
      become: no
      shell: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml

    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Save join command locally
      local_action: 
        module: copy 
        content: "{{ join_command_raw.stdout }}" 
        dest: "/tmp/k8s_join_command"
      become: no # ВАЖНО: Отключаем sudo для локального действия внутри контейнера
